// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to be re-generated by the CLI.
//
// This file contains the configuration for the Firebase project.
// It is used to initialize the Firebase SDK.
//
// YOU MUST NOT MODIFY THIS FILE MANUALLY.

// This configuration is for a project in the Project anubhav-S2-421303,
// and is not intended for production use. It is for local development only.

export const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};
