// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to be re-generated by the CLI.
//
// This file contains the configuration for the Firebase project.
// It is used to initialize the Firebase SDK.
//
// YOU MUST NOT MODIFY THIS FILE MANUALLY.

// This configuration is for a project in the Project website-data-dd505,
// and is not intended for production use. It is for local development only.

export const firebaseConfig = {
  apiKey: "AIzaSyCBZXJ2_gNsaAr5gq9S-OIeBRziCe4QN4c",
  authDomain: "website-data-dd505.firebaseapp.com",
  projectId: "website-data-dd505",
  storageBucket: "website-data-dd505.appspot.com",
  messagingSenderId: "282951914168",
  appId: "1:282951914168:web:307039a355eb6b8e2dda4d",
  measurementId: "G-WTHJNQC9M3"
};
